spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/strapi
    username: strapi
    password: strapi
jwt:
  expiration: 86400000
  secret: VMAYJfMr6b3b5vHo0TiGLPEBjHndLuJRT8OElbanBiGCBmlOI8j0ts3EkyzrUBdlK88NGx7LEumdzQt2ACoySlON2Fp6lTASCeXx0F3RQvKF6VftFLBgbcBNRm7qUyfDExiVrzf0bAPGsEzxWFuCoIU7T9JfquKyOCfXSUukSKe9PmJiL923hwSbzVfYd9E7td875ViQ5rxQuZrtrGZuLkePbKTt5qpBFKVqXCFF2ezqHxANZH9BR8X6iYZHzJTG


dineduc:
  cms:
    name: "strapi"
    base-url: "http://localhost:1337"
    modules-path-url: "/modules"
    lessons-path-url: "/lessons"
    trails-path-url: "/trails"